/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_dialogs;

import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.Proyecto;
import models.Tarea;

/**
 *
 * @author Isra
 */
public class DialogTasks extends javax.swing.JDialog {
    private Tarea tareas;
    private Proyecto proj;
    private DefaultTableModel modelo;
    private ResultSet results;
    
    /**
     * Creates new form ViewTasks
     */
    public DialogTasks(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        proj = new Proyecto();
        tareas = new Tarea();
        modelo = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Responsable");
        modelo.addColumn("Email");
        modelo.addColumn("Status");
        this.jTable1.setModel(modelo);
        
        // COLORES DE LAS ROWS
        this.jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean isSelected, boolean hasFocus, int row, int col) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                        
                String status = (String)table.getModel().getValueAt(row, 5);
                if (isSelected) {
                    c.setBackground(Color.blue.darker());
                    c.setForeground(Color.white);
                }else{
                    if (col == 5) {
                        c.setForeground(Color.white);
                        switch(status){
                            case "Pendiente":
                                c.setBackground(Color.orange.darker());
                            break;
                            case "Cancelada":
                                c.setBackground(Color.red.darker());
                            break;
                            case "Terminada":
                                c.setBackground(Color.green.darker());
                            break;
                        }
                    }else{
                        c.setBackground(null);
                        c.setForeground(Color.black);
                    }
                }
                return this;
            }   
        });
    }
    
    public void setTasks(int proyecto_id){
        this.setLocationRelativeTo(null);
        modelo.setRowCount(0);
        results=tareas.findByProjectId(proyecto_id);
        try{
            while(results.next()){
                modelo.addRow(new Object[]{
                    results.getString("id"),
                    results.getString("titulo"),
                    results.getString("descripcion"),
                    ( results.getString("u_nombre") != null 
                            && 
                            !results.getString("u_nombre").isEmpty()
                            &&
                            results.getString("u_apellidos") != null
                            &&
                            !results.getString("u_apellidos").isEmpty()
                    ) ? results.getString("u_nombre")+" "+results.getString("u_apellidos") : "No asignado.",
                    (results.getString("u_email") != null && !results.getString("u_email").isEmpty()) ? results.getString("u_email") : " - ",
                    (results.getInt("status") == 1 ? "Pendiente" : (results.getInt("status") == 2) ? "Cancelada" : "Terminada" )
                });
            }
            this.jTable1.setModel(modelo);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tareas del proyecto");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogTasks dialog = new DialogTasks(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
