/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import session_manager.Session;
import java.util.Locale;
import models.Tarea;
import models.Usuario;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author cesargustavo
 */
public class ViewDashboardUser extends javax.swing.JPanel {
    Tarea task;
    Usuario usr;
    ResultSet results;
    
    ChartPanel pieTasks;
    JFreeChart chartT;
    DefaultPieDataset dsT;
    
    PiePlot plot;
    /**
     * Creates new form General
     */
    public ViewDashboardUser() {
        initComponents();
        task = new Tarea();
        usr = new Usuario();
        dsT = new DefaultPieDataset();
    }
    
    public final void generatePieTasks(){
        results = task.getAllPieUser(Session.getId());
        try{
            dsT.clear();
            while(results.next()){
                switch(results.getInt("status")){
                    case 1:
                        this.txt_pendientes.setText("Pendientes en total: "+results.getString("cuenta"));
                        dsT.setValue("Pendientes", results.getInt("cuenta"));
                    break;
                    
                    case 2:
                        this.txt_canceladas.setText("Canceladas: "+results.getString("cuenta"));
                        dsT.setValue("Canceladas", results.getInt("cuenta"));
                    break;
                    
                    case 3:
                        this.txt_terminadas.setText("Terminadas: "+results.getString("cuenta"));
                        dsT.setValue("Terminadas", results.getInt("cuenta"));
                    break;
                }
            }
            
            chartT = ChartFactory.createPieChart("Mis tareas", dsT, true, true, Locale.ITALY);
            pieTasks = new ChartPanel(chartT);
            panelGraficas.add(pieTasks,BorderLayout.CENTER);
            panelGraficas.validate();
            pieTasks.setSize((this.getSize().width-50) / 2, this.getSize().height / 2);
            pieTasks.setLocation(this.getSize().width/4,0);
            plot = (PiePlot) chartT.getPlot();
            plot.setSectionPaint("Pendientes", Color.orange);
            plot.setSectionPaint("Canceladas", Color.red);
            plot.setSectionPaint("Terminadas", Color.green);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    public final void actualizarDashboard(){
        this.txt_pendientes.setText("Pendientes en total: 0");
        this.txt_canceladas.setText("Canceladas: 0");
        this.txt_terminadas.setText("Terminadas: 0");
        
        this.txt_pendientes.setForeground(Color.orange.darker());
        this.txt_canceladas.setForeground(Color.red.darker());
        this.txt_terminadas.setForeground(Color.green.darker());
        
        results = task.getAllPieUser(Session.getId());
        try{
            if (results.first()) {
                this.generatePieTasks();
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelGraficas = new javax.swing.JPanel();
        txt_pendientes = new javax.swing.JLabel();
        txt_canceladas = new javax.swing.JLabel();
        txt_terminadas = new javax.swing.JLabel();

        PanelGeneral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout panelGraficasLayout = new javax.swing.GroupLayout(panelGraficas);
        panelGraficas.setLayout(panelGraficasLayout);
        panelGraficasLayout.setHorizontalGroup(
            panelGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGraficasLayout.setVerticalGroup(
            panelGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        txt_pendientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_pendientes.setText("Pendientes en total: 0");

        txt_canceladas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_canceladas.setText("Canceladas: 0");

        txt_terminadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_terminadas.setText("Terminadas: 0");

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGraficas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txt_canceladas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_terminadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_canceladas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_terminadas)
                .addGap(18, 18, 18)
                .addComponent(panelGraficas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelGraficas;
    private javax.swing.JLabel txt_canceladas;
    private javax.swing.JLabel txt_pendientes;
    private javax.swing.JLabel txt_terminadas;
    // End of variables declaration//GEN-END:variables
}
