/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import models.Proyecto;
import view_dialogs.EditingProject;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import view_dialogs.DialogTasks;
/**
 *
 * @author cesargustavo
 */
public class ViewProyectos extends javax.swing.JPanel {
    private Proyecto proj;
    private DefaultTableModel modelo;
    private ResultSet results; 
    private EditingProject edp;
    private DialogTasks dtsk;
    
    /**
     * Creates new form Panel1
     * @param _frame
     */
    public ViewProyectos(AdminView _frame) {
        initComponents();
        proj = new Proyecto();
        edp = new EditingProject(_frame,true);
        edp.setViewProyectos(this);
        dtsk=new DialogTasks(_frame,true);
        
        modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Tareas");
        modelo.addColumn("Status");
        this.jTable1.setModel(modelo);
        
        // COLORES DE LAS ROWS
        this.jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean isSelected, boolean hasFocus, int row, int col) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                        
                String status = (String)table.getModel().getValueAt(row, 4);
                if (isSelected) {
                    c.setBackground(Color.blue.darker());
                    c.setForeground(Color.white);
                }else{
                    if (col == 4) {
                        c.setForeground(Color.white);
                        switch(status){
                            case "Pendiente":
                                c.setBackground(Color.orange.darker());
                            break;
                            case "Cancelado":
                                c.setBackground(Color.red.darker());
                            break;
                            case "Terminado":
                                c.setBackground(Color.green.darker());
                            break;
                        }
                    }else{
                        c.setBackground(null);
                        c.setForeground(Color.black);
                    }
                }
                return this;
            }   
        });
        
        this.jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public final void actualizarTabla(){
        modelo.setRowCount(0);
        results=proj.getAll();
        try{
            while(results.next()){
                modelo.addRow(new Object[]{
                    results.getString("id"),
                    results.getString("titulo"),
                    results.getString("descripcion"),
                    results.getString("count_tareas"),
                    (results.getInt("status") == 1 ? "Pendiente" : (results.getInt("status") == 2) ? "Cancelado" : "Terminado" )
                });
            }
            this.jTable1.setModel(modelo);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAgregarProyecto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Descripcion = new javax.swing.JTextField();
        Titulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Proyectos1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editarProj = new javax.swing.JButton();
        Proyectos2 = new javax.swing.JButton();

        PanelAgregarProyecto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Proyectos");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        Descripcion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Descripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        Titulo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Descripcion:");

        Proyectos1.setBackground(new java.awt.Color(0, 42, 73));
        Proyectos1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Proyectos1.setForeground(new java.awt.Color(255, 255, 255));
        Proyectos1.setText("Agregar");
        Proyectos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proyectos1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        editarProj.setBackground(new java.awt.Color(0, 42, 73));
        editarProj.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        editarProj.setForeground(new java.awt.Color(255, 255, 255));
        editarProj.setText("Editar");
        editarProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProjActionPerformed(evt);
            }
        });

        Proyectos2.setBackground(new java.awt.Color(0, 42, 73));
        Proyectos2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Proyectos2.setForeground(new java.awt.Color(255, 255, 255));
        Proyectos2.setText("Ver tareas");
        Proyectos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proyectos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAgregarProyectoLayout = new javax.swing.GroupLayout(PanelAgregarProyecto);
        PanelAgregarProyecto.setLayout(PanelAgregarProyectoLayout);
        PanelAgregarProyectoLayout.setHorizontalGroup(
            PanelAgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgregarProyectoLayout.createSequentialGroup()
                        .addGroup(PanelAgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Proyectos1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelAgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarProyectoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Proyectos2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarProj, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelAgregarProyectoLayout.setVerticalGroup(
            PanelAgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarProyectoLayout.createSequentialGroup()
                .addGroup(PanelAgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgregarProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Proyectos1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAgregarProyectoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarProj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Proyectos2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAgregarProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAgregarProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void Proyectos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proyectos1ActionPerformed
        // TODO add your handling code here:
        if ( !"".equals(this.Titulo.getText()) && !"".equals(this.Descripcion.getText()) ) {
            proj.insert(this.Titulo.getText(),this.Descripcion.getText(),1);
            JOptionPane.showMessageDialog(this, "Proyecto '"+this.Titulo.getText()+"' registrado con exito!");
            this.Titulo.setText("");
            this.Descripcion.setText("");
            this.actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Llenar los campos!");
        }
    }//GEN-LAST:event_Proyectos1ActionPerformed

    private void editarProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProjActionPerformed
        // TODO add your handling code here:
        if (this.jTable1.getSelectedRowCount() > 0) {
            this.edp.setProjectData( Integer.valueOf( String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(), 0) ) ) );
            this.edp.setVisible(true);
        }else
            JOptionPane.showMessageDialog(this, "Seleccione un proyecto!");
    }//GEN-LAST:event_editarProjActionPerformed

    private void Proyectos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proyectos2ActionPerformed
        // TODO add your handling code here:
        if (this.jTable1.getSelectedRowCount() > 0) {
            this.dtsk.setTasks( Integer.valueOf( String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(), 0) ) ) );
            this.dtsk.setVisible(true);
        }else
            JOptionPane.showMessageDialog(this, "Seleccione un proyecto!");
    }//GEN-LAST:event_Proyectos2ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descripcion;
    private javax.swing.JPanel PanelAgregarProyecto;
    private javax.swing.JButton Proyectos1;
    private javax.swing.JButton Proyectos2;
    private javax.swing.JTextField Titulo;
    private javax.swing.JButton editarProj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
